/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Head_1: THREE.Mesh
    Hat_Layer: THREE.Mesh
    Body_1: THREE.Mesh
    Body_Layer: THREE.Mesh
    Right_Arm: THREE.Mesh
    Right_Arm_Layer: THREE.Mesh
    Left_Arm: THREE.Mesh
    Left_Arm_Layer: THREE.Mesh
    Right_Leg: THREE.Mesh
    Right_Leg_Layer: THREE.Mesh
    Left_Leg: THREE.Mesh
    Left_Leg_Layer: THREE.Mesh
    Tail: THREE.Mesh
    Left_ear: THREE.Mesh
    Right_ear: THREE.Mesh
    Snout: THREE.Mesh
    Up_ears: THREE.Mesh
  }
  materials: {}
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/skin.gltf') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 1.5, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Head_1.geometry}
          material={nodes.Head_1.material}
          position={[0, -1.5, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Hat_Layer.geometry}
          material={nodes.Hat_Layer.material}
          position={[0, -1.5, 0]}
        />
      </group>
      <group position={[0, 1.5, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_1.geometry}
          material={nodes.Body_1.material}
          position={[0, -1.5, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Body_Layer.geometry}
          material={nodes.Body_Layer.material}
          position={[0, -1.5, 0]}
        />
      </group>
      <group position={[0.313, 1.375, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Right_Arm.geometry}
          material={nodes.Right_Arm.material}
          position={[-0.313, -1.375, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Right_Arm_Layer.geometry}
          material={nodes.Right_Arm_Layer.material}
          position={[-0.313, -1.375, 0]}
        />
      </group>
      <group position={[-0.313, 1.375, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Left_Arm.geometry}
          material={nodes.Left_Arm.material}
          position={[0.313, -1.375, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Left_Arm_Layer.geometry}
          material={nodes.Left_Arm_Layer.material}
          position={[0.313, -1.375, 0]}
        />
      </group>
      <group position={[0.119, 0.75, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Right_Leg.geometry}
          material={nodes.Right_Leg.material}
          position={[-0.119, -0.75, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Right_Leg_Layer.geometry}
          material={nodes.Right_Leg_Layer.material}
          position={[-0.119, -0.75, 0]}
        />
      </group>
      <group position={[-0.119, 0.75, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Left_Leg.geometry}
          material={nodes.Left_Leg.material}
          position={[0.119, -0.75, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Left_Leg_Layer.geometry}
          material={nodes.Left_Leg_Layer.material}
          position={[0.119, -0.75, 0]}
        />
      </group>
      <group position={[-0.5, 0, -0.5]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tail.geometry}
          material={nodes.Tail.material}
          position={[0.438, 0.625, 1.813]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Left_ear.geometry}
          material={nodes.Left_ear.material}
          position={[0, 1.75, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Right_ear.geometry}
          material={nodes.Right_ear.material}
          position={[0.75, 1.75, 0.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Snout.geometry}
          material={nodes.Snout.material}
          position={[0.438, 1.5, 0.125]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Up_ears.geometry}
          material={nodes.Up_ears.material}
          position={[0, 2, 0.375]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/skin.gltf')
